---
# tasks file for mysql_db
- name: Install MySQL database
  apt: name={{ item }} state=present
  with_items:
    - mysql-server
    - mysql-client

- name: Start MySQL Service
  service:
    name: mysql
    state: started
    enabled: yes

- name: Restart MySQL
  shell: /etc/init.d/mysql restart
  #To correct a bug on Ubuntu 16

- name: Create Application Database
  mysql_db: 
    name: '{{ db_name }}'
    state: present

- name: Create Database user
  mysql_user:
    name: '{{ db_user }}'
    password: '{{ db_password }}'
    priv: '*.*:ALL'
    state: present
    host: '%'